name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_and_deploy_main:
    name: Rust project for main branch
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - uses: extractions/setup-just@v1
        with:
          just-version: "1.13"

      - name: Setup styles
        run: just setup-styles

      - name: Setup SBOM
        run: just sbom

      - name: Build
        run: trunk build --features=yew-preview --release --public-url /konnektoren-yew/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          keep_files: true
